# Generated by Django 4.2.6 on 2025-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cands',
            fields=[
                ('id_ct', models.AutoField(primary_key=True, serialize=False)),
                ('name_can', models.CharField(max_length=50)),
                ('corporation', models.CharField(max_length=50)),
                ('cc', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 't_cands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coms',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('name_com', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_coms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divipole',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dd', models.IntegerField(blank=True, db_column='DD', null=True)),
                ('mm', models.IntegerField(blank=True, db_column='MM', null=True)),
                ('zz', models.IntegerField(blank=True, db_column='ZZ', null=True)),
                ('pp', models.CharField(blank=True, db_column='PP', max_length=5, null=True)),
                ('depto', models.CharField(blank=True, db_column='DEPTO', max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, db_column='MUNICIPIO', max_length=50, null=True)),
                ('nombre_puesto', models.CharField(blank=True, db_column='NOMBRE_PUESTO', max_length=50, null=True)),
                ('mujeres', models.FloatField(blank=True, db_column='MUJERES', null=True)),
                ('hombres', models.FloatField(blank=True, db_column='HOMBRES', null=True)),
                ('total', models.FloatField(blank=True, db_column='TOTAL', null=True)),
                ('mesas', models.IntegerField(blank=True, db_column='MESAS', null=True)),
                ('cod_com', models.IntegerField(blank=True, db_column='COD.COM', null=True)),
                ('comuna_localidad', models.CharField(blank=True, db_column='COMUNA/LOCALIDAD', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=50, null=True)),
                ('mesas_ocupadas', models.JSONField(blank=True, db_column='MESAS_OCUPADAS', default=list, null=True)),
            ],
            options={
                'db_table': 'divipole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dpts',
            fields=[
                ('id_d', models.AutoField(primary_key=True, serialize=False)),
                ('cod_dep', models.CharField(max_length=50)),
                ('name_dept', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_dpts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Muns',
            fields=[
                ('id_m', models.AutoField(primary_key=True, serialize=False)),
                ('cod_mun', models.CharField(max_length=50)),
                ('name_mun', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_muns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('cod_zona', models.CharField(max_length=50)),
                ('cod_post', models.CharField(max_length=50)),
                ('name_post', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id_t', models.AutoField(primary_key=True, serialize=False)),
                ('name_table', models.CharField(max_length=50)),
                ('type_witnesse', models.CharField(blank=True, max_length=25, null=True)),
                ('cc', models.CharField(blank=True, max_length=25, null=True)),
                ('p_name', models.CharField(max_length=25)),
                ('s_name', models.CharField(blank=True, max_length=25, null=True)),
                ('p_last_name', models.CharField(max_length=25)),
                ('s_last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('save_testigos', models.IntegerField(blank=True, null=True)),
                ('date_creacion', models.DateField(blank=True, null=True)),
                ('date_export', models.DateField(blank=True, null=True)),
                ('status_export', models.IntegerField()),
                ('status_error', models.IntegerField(blank=True, null=True)),
                ('desc_error', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 't_tables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_user', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_t', models.AutoField(primary_key=True, serialize=False)),
                ('name_table', models.CharField(max_length=50)),
                ('type_witnesse', models.CharField(blank=True, max_length=25, null=True)),
                ('cc', models.CharField(blank=True, max_length=25, null=True)),
                ('p_name', models.CharField(max_length=25)),
                ('s_name', models.CharField(blank=True, max_length=25, null=True)),
                ('p_last_name', models.CharField(max_length=25)),
                ('s_last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('save_testigos', models.IntegerField(blank=True, null=True)),
                ('id_user', models.IntegerField()),
                ('date_creacion', models.DateField(blank=True, null=True)),
                ('date_export', models.DateField(blank=True, null=True)),
                ('status_export', models.IntegerField()),
                ('status_error', models.IntegerField(blank=True, null=True)),
                ('desc_error', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 't_zonas',
                'managed': False,
            },
        ),
    ]
