# Generated by Django 5.2.6 on 2025-09-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testigos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='id_post',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_candidato',
        ),
        migrations.AddField(
            model_name='zonas',
            name='mesa',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='zonas',
            name='puesto',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
