# Generated by Django 4.2.6 on 2025-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testigos', '0002_remove_tables_id_post_remove_tables_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonas',
            name='zona',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='zonas',
            name='mesa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='zonas',
            name='puesto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
