# Generated by Django 4.2.6 on 2025-09-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testigos', '0003_zonas_zona_alter_zonas_mesa_alter_zonas_puesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cands',
            options={'ordering': ['name_can'], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='zonas',
            options={'ordering': ['type_witnesse'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.AlterField(
            model_name='zonas',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
