# Generated by Django 4.2.6 on 2025-09-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testigos', '0004_alter_cands_options_alter_zonas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonas',
            name='id_z_com',
            field=models.ForeignKey(blank=True, db_column='id_z_com', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testigos.coms'),
        ),
    ]
