# Generated by Django 4.2.6 on 2025-09-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testigos', '0005_zonas_id_z_com'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coms',
            options={'verbose_name': 'Comuna/Localidad', 'verbose_name_plural': 'Comunidades/Localidades'},
        ),
        migrations.AlterModelOptions(
            name='divipole',
            options={'verbose_name': 'Divipole', 'verbose_name_plural': 'Divipole'},
        ),
        migrations.AlterModelOptions(
            name='dpts',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='muns',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
    ]
