# Generated by Django 4.2.6 on 2025-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testigos', '0006_alter_coms_options_alter_divipole_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonas',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonas',
            name='nombre_tipo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zonas',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
